/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import 'sst';
export {};
declare module 'sst' {
	export interface Resource {
		Aurelius: {
			type: 'sst.aws.SvelteKit';
			url: string;
		};
		FileUploads: {
			name: string;
			type: 'sst.aws.Bucket';
		};
		NeonUrl: {
			type: 'sst.sst.Secret';
			value: string;
		};
		StripeSecret: {
			type: 'sst.sst.Secret';
			value: string;
		};
		StripeWebhookSecret: {
			type: 'sst.sst.Secret';
			value: string;
		};
	}
}
