name: CI - Lint and Test with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SST
        uses: actions/cache@v4
        with:
          path: |
            .sst
          key: ${{runner.os}}-sst

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Run Tests
        run: bun run test:unit
