name: CI - Lint and Test with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SST
        uses: actions/cache@v4
        with:
          path: |
            .sst
          key: ${{runner.os}}-sst

      # Step 2: Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      # Step 3: Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Step 4: Run linter (Assuming you use ESLint)
      - name: Run Linter
        run: bun run lint

      - name: Start SST so tests can function
        run: |
          nohup bunx sst dev > sst.log 2>&1 &
          echo $! > sst_dev.pid
        shell: bash

      - name: Wait for SST to be ready
        run: bunx wait-on http://localhost:5173

      # Step 5: Run tests
      - name: Run Tests
        run: bun run test

      - name: Stop SST after testing
        run: kill $(cat sst_dev.pid)
        if: always()
