name: CI - Lint and Test with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache SST
      uses: actions/cache@v4
      with:
        path: |
            .sst
        key: ${{runner.os}}-sst

    # Step 2: Install Bun
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    # Step 3: Install dependencies using Bun
    - name: Install dependencies
      run: bun install

    # Step 4: Run linter (Assuming you use ESLint)
    - name: Run Linter
      run: bun run lint

    # Step 5: Run tests
    - name: Run Tests
      run: bun run test

    # Step 6: Typechecking
    - name: Run Typechecking
      run: bun run typecheck
